#!/bin/sh

# Clean up
if [ -d .git/modules/lol ]; then
    echo "Warning: found old submodule directory .git/modules/lol"
    exit 1
fi

# Check that the repository is properly set up
if [ ! -x "./src/3rdparty/lolengine/bootstrap" ]; then
cat << EOF
Error: cannot execute src/3rdparty/lolengine/bootstrap

Did you configure the Lol Engine submodule? The following may help:

    git submodule update --init --recursive

EOF
    exit 1
fi

# Bootstrap this project first, using the Lol Engine script
./src/3rdparty/lolengine/bootstrap

# Then bootstrap Lol Engine itself
(cd src/3rdparty/lolengine && ./bootstrap)

