// cpp -DZEXPORT=ZEXPORT < zlib.h | sed -ne 's/.*ZEXPORTV*A* *\([^ (]*\).*/#define \1 \1_gz8/p'
#define zlibVersion zlibVersion_gz8
#define deflate deflate_gz8
#define deflateEnd deflateEnd_gz8
#define inflate inflate_gz8
#define inflateEnd inflateEnd_gz8
#define deflateSetDictionary deflateSetDictionary_gz8
#define deflateGetDictionary deflateGetDictionary_gz8
#define deflateCopy deflateCopy_gz8
#define deflateReset deflateReset_gz8
#define deflateParams deflateParams_gz8
#define deflateTune deflateTune_gz8
#define deflateBound deflateBound_gz8
#define deflatePending deflatePending_gz8
#define deflatePrime deflatePrime_gz8
#define deflateSetHeader deflateSetHeader_gz8
#define inflateSetDictionary inflateSetDictionary_gz8
#define inflateGetDictionary inflateGetDictionary_gz8
#define inflateSync inflateSync_gz8
#define inflateCopy inflateCopy_gz8
#define inflateReset inflateReset_gz8
#define inflateReset2 inflateReset2_gz8
#define inflatePrime inflatePrime_gz8
#define inflateMark inflateMark_gz8
#define inflateGetHeader inflateGetHeader_gz8
#define inflateBack inflateBack_gz8
#define inflateBackEnd inflateBackEnd_gz8
#define zlibCompileFlags zlibCompileFlags_gz8
#define compress compress_gz8
#define compress2 compress2_gz8
#define compressBound compressBound_gz8
#define uncompress uncompress_gz8
#define uncompress2 uncompress2_gz8
#define gzdopen gzdopen_gz8
#define gzbuffer gzbuffer_gz8
#define gzsetparams gzsetparams_gz8
#define gzread gzread_gz8
#define gzfread gzfread_gz8
#define gzwrite gzwrite_gz8
#define gzfwrite gzfwrite_gz8
#define gzputs gzputs_gz8
#define gzgets gzgets_gz8
#define gzputc gzputc_gz8
#define gzgetc gzgetc_gz8
#define gzungetc gzungetc_gz8
#define gzflush gzflush_gz8
#define gzrewind gzrewind_gz8
#define gzeof gzeof_gz8
#define gzdirect gzdirect_gz8
#define gzclose gzclose_gz8
#define gzclose_r gzclose_r_gz8
#define gzclose_w gzclose_w_gz8
#define gzerror gzerror_gz8
#define gzclearerr gzclearerr_gz8
#define adler32 adler32_gz8
#define adler32_z adler32_z_gz8
#define crc32 crc32_gz8
#define crc32_z crc32_z_gz8
#define deflateInit_ deflateInit__gz8
#define inflateInit_ inflateInit__gz8
#define deflateInit2_ deflateInit2__gz8
#define inflateInit2_ inflateInit2__gz8
#define inflateBackInit_ inflateBackInit__gz8
#define gzgetc_ gzgetc__gz8
#define gzopen gzopen_gz8
#define gzseek gzseek_gz8
#define gztell gztell_gz8
#define gzoffset gzoffset_gz8
#define adler32_combine adler32_combine_gz8
#define crc32_combine crc32_combine_gz8
#define zError zError_gz8
#define inflateSyncPoint inflateSyncPoint_gz8
#define get_crc_table get_crc_table_gz8
#define inflateUndermine inflateUndermine_gz8
#define inflateValidate inflateValidate_gz8
#define inflateCodesUsed inflateCodesUsed_gz8
#define inflateResetKeep inflateResetKeep_gz8
#define deflateResetKeep deflateResetKeep_gz8
